<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = PATH_site;

return array(
    'ArminVieweg\\Dce\\' => array($typo3InstallDir . 'typo3conf/ext/dce/Classes'),
    'DmitryDulepov\\Realurl\\' => array($typo3InstallDir . 'typo3conf/ext/realurl/Classes'),
    'KayStrobach\\DyncssLess\\' => array($typo3InstallDir . 'typo3conf/ext/dyncss_less/Classes'),
    'KayStrobach\\Dyncss\\' => array($typo3InstallDir . 'typo3conf/ext/dyncss/Classes'),
    'Machwert\\Carashtheme\\' => array($typo3InstallDir . 'typo3conf/ext/carashtheme/Classes'),
    'Machwert\\MwDummy\\' => array($typo3InstallDir . 'typo3conf/ext/mw_dummy/Classes'),
);
