<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = PATH_site;

return array(
    'DmitryDulepov\\Realurl\\Cache\\CacheFactory' => $typo3InstallDir . 'typo3conf/ext/realurl/Classes/Cache/CacheFactory.php',
    'DmitryDulepov\\Realurl\\Cache\\CacheInterface' => $typo3InstallDir . 'typo3conf/ext/realurl/Classes/Cache/CacheInterface.php',
    'DmitryDulepov\\Realurl\\Cache\\DatabaseCache' => $typo3InstallDir . 'typo3conf/ext/realurl/Classes/Cache/DatabaseCache.php',
    'DmitryDulepov\\Realurl\\Cache\\PathCacheEntry' => $typo3InstallDir . 'typo3conf/ext/realurl/Classes/Cache/PathCacheEntry.php',
    'DmitryDulepov\\Realurl\\Cache\\UrlCacheEntry' => $typo3InstallDir . 'typo3conf/ext/realurl/Classes/Cache/UrlCacheEntry.php',
    'DmitryDulepov\\Realurl\\Configuration\\AutomaticConfigurator' => $typo3InstallDir . 'typo3conf/ext/realurl/Classes/Configuration/AutomaticConfigurator.php',
    'DmitryDulepov\\Realurl\\Configuration\\ConfigurationReader' => $typo3InstallDir . 'typo3conf/ext/realurl/Classes/Configuration/ConfigurationReader.php',
    'DmitryDulepov\\Realurl\\Controller\\AliasesController' => $typo3InstallDir . 'typo3conf/ext/realurl/Classes/Controller/AliasesController.php',
    'DmitryDulepov\\Realurl\\Controller\\BackendModuleController' => $typo3InstallDir . 'typo3conf/ext/realurl/Classes/Controller/BackendModuleController.php',
    'DmitryDulepov\\Realurl\\Controller\\OverviewController' => $typo3InstallDir . 'typo3conf/ext/realurl/Classes/Controller/OverviewController.php',
    'DmitryDulepov\\Realurl\\Controller\\PathCacheController' => $typo3InstallDir . 'typo3conf/ext/realurl/Classes/Controller/PathCacheController.php',
    'DmitryDulepov\\Realurl\\Controller\\UrlCacheController' => $typo3InstallDir . 'typo3conf/ext/realurl/Classes/Controller/UrlCacheController.php',
    'DmitryDulepov\\Realurl\\Decoder\\UrlDecoder' => $typo3InstallDir . 'typo3conf/ext/realurl/Classes/Decoder/UrlDecoder.php',
    'DmitryDulepov\\Realurl\\Domain\\Model\\Alias' => $typo3InstallDir . 'typo3conf/ext/realurl/Classes/Domain/Model/Alias.php',
    'DmitryDulepov\\Realurl\\Domain\\Model\\PathCacheEntry' => $typo3InstallDir . 'typo3conf/ext/realurl/Classes/Domain/Model/PathCacheEntry.php',
    'DmitryDulepov\\Realurl\\Domain\\Model\\UrlCacheEntry' => $typo3InstallDir . 'typo3conf/ext/realurl/Classes/Domain/Model/UrlCacheEntry.php',
    'DmitryDulepov\\Realurl\\Domain\\Repository\\AbstractRepository' => $typo3InstallDir . 'typo3conf/ext/realurl/Classes/Domain/Repository/AbstractRepository.php',
    'DmitryDulepov\\Realurl\\Domain\\Repository\\AliasRepository' => $typo3InstallDir . 'typo3conf/ext/realurl/Classes/Domain/Repository/AliasRepository.php',
    'DmitryDulepov\\Realurl\\Domain\\Repository\\PathCacheEntryRepository' => $typo3InstallDir . 'typo3conf/ext/realurl/Classes/Domain/Repository/PathCacheEntryRepository.php',
    'DmitryDulepov\\Realurl\\Domain\\Repository\\UrlCacheEntryRepository' => $typo3InstallDir . 'typo3conf/ext/realurl/Classes/Domain/Repository/UrlCacheEntryRepository.php',
    'DmitryDulepov\\Realurl\\EncodeDecoderBase' => $typo3InstallDir . 'typo3conf/ext/realurl/Classes/EncodeDecoderBase.php',
    'DmitryDulepov\\Realurl\\Encoder\\UrlEncoder' => $typo3InstallDir . 'typo3conf/ext/realurl/Classes/Encoder/UrlEncoder.php',
    'DmitryDulepov\\Realurl\\Evaluator\\SegmentFieldCleaner' => $typo3InstallDir . 'typo3conf/ext/realurl/Classes/Evaluator/SegmentFieldCleaner.php',
    'DmitryDulepov\\Realurl\\Exceptions\\InvalidLanguageParameterException' => $typo3InstallDir . 'typo3conf/ext/realurl/Classes/Exceptions/InvalidLanguageParameterException.php',
    'DmitryDulepov\\Realurl\\Hooks\\DataHandler' => $typo3InstallDir . 'typo3conf/ext/realurl/Classes/Hooks/DataHandler.php',
    'DmitryDulepov\\Realurl\\Utility' => $typo3InstallDir . 'typo3conf/ext/realurl/Classes/Utility.php',
    'DmitryDulepov\\Realurl\\ViewHelpers\\LanguageFromIdViewHelper' => $typo3InstallDir . 'typo3conf/ext/realurl/Classes/ViewHelpers/LanguageFromIdViewHelper.php',
    'DmitryDulepov\\Realurl\\ViewHelpers\\SetVariableViewHelper' => $typo3InstallDir . 'typo3conf/ext/realurl/Classes/ViewHelpers/SetVariableViewHelper.php',
    'DmitryDulepov\\Realurl\\ViewHelpers\\TranslateToJsonViewHelper' => $typo3InstallDir . 'typo3conf/ext/realurl/Classes/ViewHelpers/TranslateToJsonViewHelper.php',
    'Machwert\\Carashtheme\\Controller\\CustomElementController' => $typo3InstallDir . 'typo3conf/ext/carashtheme/Classes/Controller/CustomElementController.php',
    'Machwert\\MwDummy\\Controller\\CustomElementController' => $typo3InstallDir . 'typo3conf/ext/mw_dummy/Classes/Controller/CustomElementController.php',
    'Machwert\\MwDummy\\ViewHelpers\\FalViewHelper' => $typo3InstallDir . 'typo3conf/ext/mw_dummy/Classes/ViewHelpers/FalViewHelper.php',
    'Machwert\\MwDummy\\ViewHelpers\\SlideshowViewHelper' => $typo3InstallDir . 'typo3conf/ext/mw_dummy/Classes/ViewHelpers/SlideshowViewHelper.php',
);
