<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = PATH_site;

return array(
    'DmitryDulepov\\Realurl\\' => array($typo3InstallDir . 'typo3conf/ext/realurl/Classes'),
    'Machwert\\Carashtheme\\' => array($typo3InstallDir . 'typo3conf/ext/carashtheme/Classes'),
    'Machwert\\MwDummy\\' => array($typo3InstallDir . 'typo3conf/ext/mw_dummy/Classes'),
);
